Request_gpus = 1
# requirements = (CUDADeviceName != "Tesla K40m")
# requirements = (CUDADeviceName == "Quadro RTX 6000")
# requirements = (CUDADeviceName == "Titan Xp")
# requirements = (CUDADeviceName == "NVIDIA A40") || (CUDADeviceName == "Quadro RTX 6000")
requirements = (CUDADeviceName == "NVIDIA A40")

# Request_cpus = 4
# Request_cpus = 8
Request_cpus = 16
# Request_cpus = 32
# Request_cpus = 40
# Request_cpus = 12
# Request_cpus = 32
Queue
